blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
     path('<slug:slug>', views.blog_details, name='blog_details'),
   
]

lappyng_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from lappyng_app import views
from django.urls import path, include
from filebrowser.sites import site


urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('posts/', include('blog.urls')),
    path('page/<slug:slug>/', views.detail_page, name='single_page'),
    path('contact/', views.contact, name='contact'),
    path('products/', include('lappyng_app.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root =settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from newsletter import views

app_name = 'newsletter'

urlpatterns = [
    path('', views.newsletters_email, name='newsletters_email'),
    path('letter', views.letter, name='letter'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
]

newsletter/models.py
from django.db import models
from lappyng_app.models import *
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse

# Create your models here.

class Subscribers(models.Model):
    email = models.EmailField()
    conf_num = models.CharField(max_length=30)
    confirmed = models.BooleanField(default=False)

    class Meta():
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.email + " (" + str(self.confirmed) + ")"


class NewsLetterCategory(models.Model):
    name = models.CharField(max_length=35)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + " " + self.created_at.strftime("%B %d, %Y")

    class Meta():
        verbose_name_plural = 'Newsletter Category'


    def send(self, request):
        subscribers = Subscribers.objects.filter(confirmed=True)
        news_letters_list = []
        news = NewsLetter.objects.filter(news_letter__id=self.id)
        for value in news:
            news_letters_list.append(
                {'title': value.product.title, 
                'content': value.product.contents, 
                'image': value.product.image1,
                'link': request.build_absolute_uri('/products/detail/')+value.product.slug,
                })

        # goes through all post and adds it to the newsletter dictionary

        for sub in subscribers:
            html_message = render_to_string('frontend/email_templates/newsletter.html', 
                {
                'news': news_letters_list, 
                'url':request.build_absolute_uri('/newsletter/delete/'),
                'email':sub.email,
                'conf':sub.conf_num
                })
            plain_message = strip_tags(html_message)
            from_email = settings.FROM_HOST
            mail.send_mail('From Lappyng', plain_message, from_email, [sub.email, ], html_message=html_message)
        return "done"
        


class NewsLetter(models.Model):
    news_letter = models.ForeignKey(NewsLetterCategory, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title

    def __repr__(self):
        return self.product.title

  

newsletter/views.py
from django.shortcuts import render
from newsletter.models import *
import random
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
# Create your views here.


def newsletters_email(request):
    return render(request, 'frontend/email_templates/text-newsletter.html')

def letter(request):
    return render(request, 'frontend/email_templates/newsletter.html')


def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)

    
def newsletters_email(request):
    data = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        data['is_taken'] = Subscribers.objects.filter(email__iexact=email, confirmed=False).exists()
        if data['is_taken']:
            data['error_message'] = 'Email already exists but yet to be confirmed.'
        else:
            sub = Subscribers(email=email, conf_num=random_digits())
            sub.save()
            args = {
                'url':request.build_absolute_uri('/newsletter/confirm/'),
                'email':sub.email,
                'conf':sub.conf_num
            }
            html_message = render_to_string('frontend/email_templates/confirm-email-result.html', args)
            plain_message = strip_tags(html_message)
            from_email = settings.FROM_HOST
            subject = 'Email ation'
            mail.send_mail(subject, plain_message, from_email, [sub.email,], html_message=html_message, fail_silently=True)
            data['success'] = 'Thanks, we have sent you a confirmation mail in your inbox, click the link to activate'    
    return JsonResponse(data)

def confirm(request):
    sub = Subscribers.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.confirmed = True

        sub.save()
        return render(request, 'frontend/email_templates/confirm-email.html', {'email': sub.email, 'action': 'added'})
    else:
        return render(request, 'frontend/email_templates/confirm-email.html', {'email': sub.email, 'action': 'denied'})

def delete(request):
    sub = Subscribers.objects.get(email=request.GET['email'])
    if sub.conf_num == request.GET['conf_num']:
        sub.delete()
        return render(request, 'website/confirm-email.html', {'email': sub.email, 'action': 'unsubscribed'})
    else:
        return render(request, 'website/confirm-email.html', {'email': sub.email, 'action': 'denied'})

templates/frontend/email_templates/confirm-email-result.html
{% extends 'frontend/email_templates/email_base.html' %}
{% load static %}

{% block title %}
Confirm Email
{% endblock %}

{% block content %}

<table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
    <tr>
        <td>
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="580" style="border-collapse: collapse;">
                <tr>
                    <td>
                        <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                            <tr>
                                <td>
                                    <!-- Space -->
                                    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                        <tr><td style="font-size: 0; line-height: 0;" height="20">&nbsp;</td></tr>
                                    </table>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" width="540" style="border-collapse: collapse;">
                                        <tr>
                                            <td>
                                            <table align="left" border="0">
                                                    <!-- Space -->
                                                    <tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
                                                    <tr>
                                                        <p width="100%" style="font-size: 15px; text-align: center; line-height: 22px; font-family:helvetica, Arial, sans-serif; color:#777777;">

                                                            <p>
Thank you for signing up for my email newsletter Please complete the process by
</p>
<a href="{{ url }}?email={{ email }}&conf_num={{ conf }}"> clicking here to confirm your registration</a>

                                                        </p>
                                                    </tr>
                                                </table>
                                                
                                                
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <!-- Space -->
                                    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                        <tr><td style="font-size: 0; line-height: 0;" height="30">&nbsp;</td></tr>				
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
					

{% endblock %}

templates/frontend/email_templates/confirm-email.html
{% extends 'frontend/email_templates/email_base.html' %}
{% load static %}

{% block title %}
Newsletter
{% endblock %}

{% block content %}

<table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
    <tr>
        <td>
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="580" style="border-collapse: collapse;">
                <tr>
                    <td>
                        <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                            <tr>
                                <td>
                                    <!-- Space -->
                                    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                        <tr><td style="font-size: 0; line-height: 0;" height="20">&nbsp;</td></tr>
                                    </table>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" width="540" style="border-collapse: collapse;">
                                        <tr>
                                            <td>
                                                                                                            <table align="left" border="0"padte=>
                                                    <!-- Space -->
                                                    <tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
                                                    <tr>
                                                        <p width="100%" style="font-size: 15px; text-align: center; line-height: 22px; font-family:helvetica, Arial, sans-serif; color:#777777;">

                                                            {% if email %}
                                                              {{ email }} has been {{ action }}
                                                            {% endif %}
                                                    </tr>
                                                </table>
                                                
                                                
                                            </td>
                                        </tr>
                                    </table>
                                    
                                    <!-- Space -->
                                    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
                                        <tr><td style="font-size: 0; line-height: 0;" height="30">&nbsp;</td></tr>				
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
	

{% endblock %}

templates/frontend/email_templates/contact-email-template.html
{% extends 'frontend/email_templates/email_base.html' %}
{% load static %}

		
{% block title %}
Contact 
{% endblock %}
	

	

				{% block content %}


					

						<table border="0"  align="center" width="600" style="border-collapse:collapse; font-size:larger; padding:50%; ">
							<tr>
								<td>
									<form action="" method="post">
									<table align="center" style="border-collapse: collapse;">
										<tr>
											<th style="border:1px solid #000;width:180px; padding: 10px;">Fields</th>
											<th style="border:1px solid #000; padding: 10px;">Data</th>
									
										</tr>
										<tr>
											<td style="border:1px solid #000;width:180px; padding: 10px;">Full Name</td>
											<td style="border:1px solid #000; padding: 10px;">{{name}}</td>
										</tr>
										<tr class="st">
											<td style="border:1px solid #000;width:180px; padding: 10px;">Email</td>
											<td style="border:1px solid #000; padding: 10px;">{{email}}</td>

										</tr>
										<tr class="st">
											<td style="border:1px solid #000;width:180px; padding: 10px;">Phone</td>
											<td style="border:1px solid #000; padding: 10px;">{{phone}}</td>

										</tr>
										<tr class="st">
											<td style="border:1px solid #000; width:180px; padding: 10px;">Message</td>
											<td style="border:1px solid #000; padding: 10px;">
													{{message}}                                               
												
											</td>
											
										</tr>

									</table>
									</form>
								</td>
							</tr>

							
									
							</table>
										
					

					
					

{% endblock %}

templates/frontend/email_templates/email_base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>{% block title %} {% endblock %}</title>
		<link rel="stylesheet" href="{% static 'frontend/css/email.css' %}">

	</head>

	<body  class="table" style="margin: 0; padding: 0;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%">
			<tr>
				<td>

					<!-- Header Top Start -->
					<table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
						<tr>
							<td>
								<table align="center" border="0" cellpadding="0" cellspacing="0" width="700" style="border-collapse: collapse;">
									<tr>
										<td align="left"  bgcolor="#272d2d">
											<!-- Space -->
											<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
											</table>
											<table align="center">
												<tr>
													<td width="25">

									
														<img src="https://res.cloudinary.com/benedict78/image/upload/v1635997720/email-templates/marker-icon-white_t5nf3s.png
														" alt="location" />
													</td>
													<td style="color: #fff; font-size: 12px; line-height: 18px; font-weight: bolder; font-family: helvetica, Arial, sans-serif;">2B, Oremeji street, Off Medical road, lkeja, Lagos.</td>
													<td width="25"></td>
													<td width="25">
														<img src="https://res.cloudinary.com/benedict78/image/upload/v1635998033/email-templates/phone-icon-white_lybanm.png" alt="location" />
													</td>
													<td style="color: #fff; font-size: 12px; line-height: 18px; font-weight: bolder; font-family: helvetica, Arial, sans-serif;">+234&nbsp;815&nbsp;603&nbsp;5584</td>
													<td width="25"></td>
													<td width="25">
														<img src="https://res.cloudinary.com/benedict78/image/upload/v1622419219/email-templates/mail-icon-white_sgqqbw.png" alt="location" />
													</td>
													<td >
														<a style="color: #fff; font-size: 12px; line-height: 18px; font-weight: bolder; font-family: helvetica, Arial, sans-serif; text-decoration:none; width: 50%;" href="mailto:info@lappy.ng">info@lappy.ng</a>
													</td>
												</tr>
											</table>
											<!-- Space -->
											<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
					<!-- Header Top End -->

					<!-- Header Start -->
					<table align="center" border="0" cellpadding="0" cellspacing="0" width="500" style="border-collapse: collapse;">
						<tr>
							<td style="padding:15px;">
								<table align="center" border="0" cellpadding="0" cellspacing="0" width="480" style="border-collapse: collapse;">
									<tr>
										<td>
											<table align="left" border="0" cellpadding="0" cellspacing="0" width="200" style="border-collapse: collapse;">
												<!-- logo -->
												<tr>
													<td align="left">
														<a href="#">
															<img src="https://res.cloudinary.com/benedict78/image/upload/v1635996553/email-templates/lappy-logo_cn6nb3.jpg" alt="Company Logo" style="display: block;padding-left: 145px;"/>
														</a>
													</td>
												</tr>
												<!-- company slogan -->
												
												<!-- <tr><td style="font-size: 0; line-height: 0;" height="15">&nbsp;</td></tr> -->
											</table>
											
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
					<hr align="center" color="black"  style="width: 50%; margin-left: 10%;"  >																																																		
					<!-- Header End -->



					{% block content%}
					{% endblock %}
					
					<!-- Footer Start -->
					<table  class="footer " align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
						<tr>
							<td>
								<table bgcolor="#ffffff" align="center" border="0" cellpadding="0" cellspacing="0" width="580" style="border-collapse: collapse;">
									<tr>
										<td>
											<!-- Space
											<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" height="30">&nbsp;</td></tr>
											</table> -->
											
											<table  align="center" border="0" cellpadding="0" cellspacing="0" width="540" style="border-collapse: collapse;">
												<tr>
													<td>
														<!-- First Column -->
														<table align="" border="0" cellpadding="0" cellspacing="0" width="250"  style="border-collapse: collapse; position: relative; ">
															<tr>
																<td style="padding-right: 300px;">
																	<!-- <a href="../html/index.html"> -->
																		<img src="https://res.cloudinary.com/benedict78/image/upload/v1635996553/email-templates/lappy-logo_cn6nb3.jpg" alt="Logo" style="display: block;   "/>
																	<!-- </a> -->
																</td>
															</tr>
														</table>
														<table align="left" border="0" cellpadding="0" cellspacing="0" width="270" style="border-collapse: collapse;">
															
															<!-- Space -->
															<!-- <tr><td style="font-size: 0; line-height: 0;" height="20">&nbsp;</td></tr>
															<tr> -->
																<td class="design1" >
																	Welcome to our About Us Page, Lappy.ng is a customer-centric platform to get the best deal on all kinds of laptops <a href="https://lappy.ng/about/">....</a>
																</td>
															</tr>
															<!-- Space -->
															<tr><td style="font-size: 0; line-height: 0;" height="15">&nbsp;</td></tr>
															<tr>
																<!-- width 45  -->
																<td style="padding-left: 10px;">
																	<table align="left"  class="tee1" cellpadding="0" cellspacing="0">
																		<tr>
																			<td>
																				<a href="https://www.facebook.com">
																					<img  class="tee" src="https://res.cloudinary.com/benedict78/image/upload/v1622418776/email-templates/facebook-icon_ulzlrp.png"  alt="Facebook"  />
																				</a>
																			</td>
																		</tr>
																	</table>
																	<table  align="left" class="tee1"  cellpadding="0" cellspacing="0" >
																		<tr>
																			<td>
																				<a href="https://www.twitter.com">
																					<img  class="tee" src="https://res.cloudinary.com/benedict78/image/upload/v1622418776/email-templates/twitter-icon_mgldqn.png"  alt="Twitter" />
																				</a>
																			</td>
																		</tr>
																	</table>
																	<table  align="left" class="tee1"  cellpadding="0" cellspacing="0" >
																		<tr>
																			<td>
																				<a href="https://plus.google.com/">
																					<img  class="tee" src="https://res.cloudinary.com/benedict78/image/upload/v1622418776/email-templates/googleplus-icon_rivl8u.png"  alt="Google+"  />
																				</a>
																			</td>
																		</tr>
																	</table>
																	<table align="left" class="tee1"  cellpadding="0" cellspacing="0">
																		<tr>
																			<td>
																				<a href="https://www.linkedin.com/">
																					<img   class="tee" src="https://res.cloudinary.com/benedict78/image/upload/v1622418776/email-templates/linkedin-icon_ahbmse.png"  alt="Linked In"  />
																				</a>
																			</td>
																		</tr>
																	</table>
																	<!-- endwidth 45 -->
																</td>
															</tr>
														</table>
														<!-- Gutter 20px -->
														<!-- <table align="left" border="0" cellpadding="0" cellspacing="0" width="40" style="border-collapse: collapse;">
															<tr>
																<td>
																	&nbsp;
																</td>
															</tr>
														</table> -->
														<!-- Second Column -->
														<table class="subfoot" cellpadding="0" cellspacing="0"; >
														
															<tr>
																<td width="22">
																	<img src="https://res.cloudinary.com/benedict78/image/upload/v1635998652/email-templates/mail-icon_pozegb.png" alt="location" />
																</td>
																<td  class="design" >2B, Oremeji street, Off Medical road, lkeja, Lagos.</td>
															</tr>
															<!-- Space -->
															<tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
															<tr>
																<td class="imgc" >
																	<img src="https://res.cloudinary.com/benedict78/image/upload/v1635998033/email-templates/phone-icon_hwgwdx.png" alt="location" />
																</td>
																<td class="design" >+234&nbsp;815&nbsp;603&nbsp;5584</td>
															</tr>
															<!-- Space -->
															<tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
															<tr>
																<td class="imgc" >
																	<img src="https://res.cloudinary.com/benedict78/image/upload/v1635998750/email-templates/fax-icon_drwtg3.png" alt="location" />
																</td>
																<td  class="design">+234&nbsp;905&nbsp;727&nbsp;7551</td>
															</tr>
															<!-- Space -->
															<tr><td style="font-size: 0; line-height: 0;" height="10">&nbsp;</td></tr>
															<tr>
																<td class="imgc" >
																	<img src="https://res.cloudinary.com/benedict78/image/upload/v1635998652/email-templates/mail-icon_pozegb.png" alt="location" />
																</td>
																<td>
																	<a class="design" href="mailto:info@lappy.ng">info@lappy.ng</a>
																</td>
															</tr>
														</table>
													</td>
												</tr>
											</table>
											<!-- Space -->
											<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" height="30">&nbsp;</td></tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>

					</table>
					<!-- Footer End -->

					<!-- Subfooter Start -->
					<table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
						<tr>
							<td>
								<table bgcolor="#f5f5f5" align="center" border="0" cellpadding="0" cellspacing="0" width="580" style="border-collapse: collapse;">
									<tr>
										<td>
											<!-- Space -->
											<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" bgcolor="#eaeaea" height="1">&nbsp;</td></tr>
												<tr><td style="font-size: 0; line-height: 0;" height="20">&nbsp;</td></tr>
											</table>
											<table align="center" border="0" cellpadding="0" cellspacing="0" width="540" style="border-collapse: collapse;">
												<tr>
													<td align="center" style="color: #999999; font-size: 14px; line-height: 18px; font-weight: normal; font-family: helvetica, Arial, sans-serif;">
														Copyright © <span id="year"></span> The Project by <a href="https://lappy.ng" style="color: #2aa4a5; font-size: 14px; line-height: 18px; font-weight: normal; font-family: helvetica, Arial, sans-serif; text-decoration:none;">lappy.ng</a>. All Rights Reserved / <a href="{% url 'newsletter:delete' %}" style="color: #2aa4a5; font-size: 14px; line-height: 18px; font-weight: normal; font-family: helvetica, Arial, sans-serif; text-decoration:none;"> Unsubscribe</a>
													</td>
												</tr>
											</table>
											<script>
												document.getElementById("year").innerHTML = new Date().getFullYear();
											</script>
											<!-- Space -->
											<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
												<tr><td style="font-size: 0; line-height: 0;" height="20">&nbsp;</td></tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>

					</table>
					<!-- Subfooter End -->
			

				</td>
			</tr>
		</table>
	</body>
</html>

templates/frontend/email_templates/newsletter.html
{% extends 'frontend/email_templates/email_base.html' %}
{% load static %}

{% block title %}
Newsletter
{% endblock %}

{% block content %}

	<!-- Banner Start -->
		<!-- row -->
		{% if news %}
			{% for n in news %}
			<table align="center" border="0" cellpadding="0" cellspacing="0" width="700" style="border-collapse: collapse;">
				<tr>
					<td>
						<!-- first column -->
						<table bgcolor="#fafafa" align="left" border="0" cellpadding="0" cellspacing="0" width="350" style="border-collapse: collapse;">
							<tr>
								<td>
									<table width="100%"  border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
										<tr>
											<td bgcolor="#ffffff" >
												<a href="#">
													<img src="{{ n.image.url }}" width="100%" alt="Section one image" style="display: block;"/>
												</a>
											</td>
										</tr>
	
									</table>
								</td>
							</tr>
						</table>
						<!-- second column -->
						<table bgcolor="#fafafa" align="right" border="0" cellpadding="0" cellspacing="0" width="350" style="border-collapse: collapse;">
							<tr>
								<td>
									<table width="100%"  border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;">
										<tr><td style="font-size: 0; line-height: 0;" height="70">&nbsp;</td></tr>
										<tr>
										<tr>
											<td  bgcolor="#ffffff" >
												<div>
													<h2 style="font-weight: bolder;">{{ n.title }}</h2>
														<p style="font-weight:normal; font-size: 23px;">
																{{ n.content|safe|truncatewords:25 }}
														</p>
														
	
												</div>
											</td>
										</tr>
	
									</table>
									<tr>
										<td>
											<table width="100" align="left" border="0" cellpadding="0"  cellspacing="0" style="border-collapse: collapse;">
												<tr>
													<td align="left">
														<a href="{{ n.link }}" style="background-color: red;color: white; font-size: 22px; font-weight: bolder; text-transform:capitalize;  padding: 10px 21px 10px 21px;"  width='500' >Readmore</a>
													</td>
												</tr>
											</table>
											<br>
											<br>
											<br>
											<br>																																																		
										</td>
										
									</tr>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<hr style="border-width: 0.6px;border-color: black; width: 50%;">																																																		
			<br>
		<!-- Banner End -->
			{% endfor %}
		{% endif %}
		
					

{% endblock %}